export const fontList = [
['fas', `ad`],
['far', `address-book`],
['fas', `address-book`],
['far', `address-card`],
['fas', `address-card`],
['fas', `adjust`],
['fas', `air-freshener`],
['fas', `align-center`],
['fas', `align-justify`],
['fas', `align-left`],
['fas', `align-right`],
['fas', `allergies`],
['fas', `ambulance`],
['fas', `american-sign-language-interpreting`],
['fas', `anchor`],
['fas', `angle-double-down`],
['fas', `angle-double-left`],
['fas', `angle-double-right`],
['fas', `angle-double-up`],
['fas', `angle-down`],
['fas', `angle-left`],
['fas', `angle-right`],
['fas', `angle-up`],
['far', `angry`],
['fas', `angry`],
['fas', `ankh`],
['fas', `apple-alt`],
['fas', `archive`],
['fas', `archway`],
// ['far', `arrow-alt-circle-down`],
// ['fas', `arrow-alt-circle-down`],
// ['far', `arrow-alt-circle-left`],
// ['fas', `arrow-alt-circle-left`],
// ['far', `arrow-alt-circle-right`],
// ['fas', `arrow-alt-circle-right`],
// ['far', `arrow-alt-circle-up`],
// ['fas', `arrow-alt-circle-up`],
// ['fas', `arrow-circle-down`],
// ['fas', `arrow-circle-left`],
// ['fas', `arrow-circle-right`],
// ['fas', `arrow-circle-up`],
// ['fas', `arrow-down`],
// ['fas', `arrow-left`],
// ['fas', `arrow-right`],
// ['fas', `arrow-up`],
// ['fas', `arrows-alt`],
// ['fas', `arrows-alt-h`],
// ['fas', `arrows-alt-v`],
// ['fas', `assistive-listening-systems`],
// ['fas', `asterisk`],
// ['fas', `at`],
// ['fas', `atlas`],
// ['fas', `atom`],
// ['fas', `audio-description`],
// ['fas', `award`],
// ['fas', `baby`],
// ['fas', `baby-carriage`],
// ['fas', `backspace`],
// ['fas', `backward`],
// ['fas', `bacon`],
// ['fas', `bahai`],
// ['fas', `balance-scale`],
// ['fas', `balance-scale-left`],
// ['fas', `balance-scale-right`],
// ['fas', `ban`],
// ['fas', `band-aid`],
// ['fas', `barcode`],
// ['fas', `bars`],
// ['fas', `baseball-ball`],
// ['fas', `basketball-ball`],
// ['fas', `bath`],
// ['fas', `battery-empty`],
// ['fas', `battery-full`],
// ['fas', `battery-half`],
// ['fas', `battery-quarter`],
// ['fas', `battery-three-quarters`],
// ['fas', `bed`],
// ['fas', `beer`],
// ['far', `bell`],
// ['fas', `bell`],
// ['far', `bell-slash`],
// ['fas', `bell-slash`],
// ['fas', `bezier-curve`],
// ['fas', `bible`],
// ['fas', `bicycle`],
// ['fas', `biking`],
// ['fas', `binoculars`],
// ['fas', `biohazard`],
// ['fas', `birthday-cake`],
// ['fas', `blender`],
// ['fas', `blender-phone`],
// ['fas', `blind`],
// ['fas', `blog`],
// ['fas', `bold`],
// ['fas', `bolt`],
// ['fas', `bomb`],
// ['fas', `bone`],
// ['fas', `bong`],
// ['fas', `book`],
// ['fas', `book-dead`],
// ['fas', `book-medical`],
// ['fas', `book-open`],
// ['fas', `book-reader`],
// ['far', `bookmark`],
// ['fas', `bookmark`],
// ['fas', `border-all`],
// ['fas', `border-none`],
// ['fas', `border-style`],
// ['fas', `bowling-ball`],
// ['fas', `box`],
// ['fas', `box-open`],
// ['fas', `box-tissue`],
// ['fas', `boxes`],
// ['fas', `braille`],
// ['fas', `brain`],
// ['fas', `bread-slice`],
// ['fas', `briefcase`],
// ['fas', `briefcase-medical`],
// ['fas', `broadcast-tower`],
// ['fas', `broom`],
// ['fas', `brush`],
// ['fas', `bug`],
// ['far', `building`],
// ['fas', `building`],
// ['fas', `bullhorn`],
// ['fas', `bullseye`],
// ['fas', `burn`],
// ['fas', `bus`],
// ['fas', `bus-alt`],
// ['fas', `business-time`],
// ['fas', `calculator`],
// ['far', `calendar`],
// ['fas', `calendar`],
// ['far', `calendar-alt`],
// ['fas', `calendar-alt`],
// ['far', `calendar-check`],
// ['fas', `calendar-check`],
// ['fas', `calendar-day`],
// ['far', `calendar-minus`],
// ['fas', `calendar-minus`],
// ['far', `calendar-plus`],
// ['fas', `calendar-plus`],
// ['far', `calendar-times`],
// ['fas', `calendar-times`],
// ['fas', `calendar-week`],
// ['fas', `camera`],
// ['fas', `camera-retro`],
// ['fas', `campground`],
// ['fas', `candy-cane`],
// ['fas', `cannabis`],
// ['fas', `capsules`],
// ['fas', `car`],
// ['fas', `car-alt`],
// ['fas', `car-battery`],
// ['fas', `car-crash`],
// ['fas', `car-side`],
// ['fas', `caravan`],
// ['fas', `caret-down`],
// ['fas', `caret-left`],
// ['fas', `caret-right`],
// ['far', `caret-square-down`],
// ['fas', `caret-square-down`],
// ['far', `caret-square-left`],
// ['fas', `caret-square-left`],
// ['far', `caret-square-right`],
// ['fas', `caret-square-right`],
// ['far', `caret-square-up`],
// ['fas', `caret-square-up`],
// ['fas', `caret-up`],
// ['fas', `carrot`],
// ['fas', `cart-arrow-down`],
// ['fas', `cart-plus`],
// ['fas', `cash-register`],
// ['fas', `cat`],
// ['fas', `certificate`],
// ['fas', `chair`],
// ['fas', `chalkboard`],
// ['fas', `chalkboard-teacher`],
// ['fas', `charging-station`],
// ['fas', `chart-area`],
// ['far', `chart-bar`],
// ['fas', `chart-bar`],
// ['fas', `chart-line`],
// ['fas', `chart-pie`],
// ['fas', `check`],
// ['far', `check-circle`],
// ['fas', `check-circle`],
// ['fas', `check-double`],
// ['far', `check-square`],
// ['fas', `check-square`],
// ['fas', `cheese`],
// ['fas', `chess`],
// ['fas', `chess-bishop`],
// ['fas', `chess-board`],
// ['fas', `chess-king`],
// ['fas', `chess-knight`],
// ['fas', `chess-pawn`],
// ['fas', `chess-queen`],
// ['fas', `chess-rook`],
// ['fas', `chevron-circle-down`],
// ['fas', `chevron-circle-left`],
// ['fas', `chevron-circle-right`],
// ['fas', `chevron-circle-up`],
// ['fas', `chevron-down`],
// ['fas', `chevron-left`],
// ['fas', `chevron-right`],
// ['fas', `chevron-up`],
// ['fas', `child`],
// ['fas', `church`],
// ['far', `circle`],
// ['fas', `circle`],
// ['fas', `circle-notch`],
// ['fas', `city`],
// ['fas', `clinic-medical`],
// ['far', `clipboard`],
// ['fas', `clipboard`],
// ['fas', `clipboard-check`],
// ['fas', `clipboard-list`],
// ['far', `clock`],
// ['fas', `clock`],
// ['far', `clone`],
// ['fas', `clone`],
// ['far', `closed-captioning`],
// ['fas', `closed-captioning`],
// ['fas', `cloud`],
// ['fas', `cloud-download-alt`],
// ['fas', `cloud-meatball`],
// ['fas', `cloud-moon`],
// ['fas', `cloud-moon-rain`],
// ['fas', `cloud-rain`],
// ['fas', `cloud-showers-heavy`],
// ['fas', `cloud-sun`],
// ['fas', `cloud-sun-rain`],
// ['fas', `cloud-upload-alt`],
// ['fas', `cocktail`],
// ['fas', `code`],
// ['fas', `code-branch`],
// ['fas', `coffee`],
// ['fas', `cog`],
// ['fas', `cogs`],
// ['fas', `coins`],
// ['fas', `columns`],
// ['far', `comment`],
// ['fas', `comment`],
// ['far', `comment-alt`],
// ['fas', `comment-alt`],
// ['fas', `comment-dollar`],
// ['far', `comment-dots`],
// ['fas', `comment-dots`],
// ['fas', `comment-medical`],
// ['fas', `comment-slash`],
// ['far', `comments`],
// ['fas', `comments`],
// ['fas', `comments-dollar`],
// ['fas', `compact-disc`],
// ['far', `compass`],
// ['fas', `compass`],
// ['fas', `compress`],
// ['fas', `compress-alt`],
// ['fas', `compress-arrows-alt`],
// ['fas', `concierge-bell`],
// ['fas', `cookie`],
// ['fas', `cookie-bite`],
// ['far', `copy`],
// ['fas', `copy`],
// ['far', `copyright`],
// ['fas', `copyright`],
// ['fas', `couch`],
// ['far', `credit-card`],
// ['fas', `credit-card`],
// ['fas', `crop`],
// ['fas', `crop-alt`],
// ['fas', `cross`],
// ['fas', `crosshairs`],
// ['fas', `crow`],
// ['fas', `crown`],
// ['fas', `crutch`],
// ['fas', `cube`],
// ['fas', `cubes`],
// ['fas', `cut`],
// ['fas', `database`],
// ['fas', `deaf`],
['fas', `democrat`],
['fas', `desktop`],
['fas', `dharmachakra`],
['fas', `diagnoses`],
['fas', `dice`],
['fas', `dice-d20`],
['fas', `dice-d6`],
['fas', `dice-five`],
['fas', `dice-four`],
['fas', `dice-one`],
['fas', `dice-six`],
['fas', `dice-three`],
['fas', `dice-two`],
['fas', `digital-tachograph`],
['fas', `directions`],
['fas', `disease`],
['fas', `divide`],
// ['far', `dizzy`],
// ['fas', `dizzy`],
// ['fas', `dna`],
// ['fas', `dog`],
// ['fas', `dollar-sign`],
// ['fas', `dolly`],
// ['fas', `dolly-flatbed`],
// ['fas', `donate`],
// ['fas', `door-closed`],
// ['fas', `door-open`],
// ['far', `dot-circle`],
// ['fas', `dot-circle`],
// ['fas', `dove`],
// ['fas', `download`],
// ['fas', `drafting-compass`],
// ['fas', `dragon`],
// ['fas', `draw-polygon`],
// ['fas', `drum`],
// ['fas', `drum-steelpan`],
// ['fas', `drumstick-bite`],
// ['fas', `dumbbell`],
// ['fas', `dumpster`],
// ['fas', `dumpster-fire`],
// ['fas', `dungeon`],
// ['far', `edit`],
// ['fas', `edit`],
// ['fas', `egg`],
// ['fas', `eject`],
// ['fas', `ellipsis-h`],
// ['fas', `ellipsis-v`],
// ['far', `envelope`],
// ['fas', `envelope`],
// ['far', `envelope-open`],
// ['fas', `envelope-open`],
// ['fas', `envelope-open-text`],
// ['fas', `envelope-square`],
// ['fas', `equals`],
// ['fas', `eraser`],
// ['fas', `ethernet`],
// ['fas', `euro-sign`],
// ['fas', `exchange-alt`],
// ['fas', `exclamation`],
// ['fas', `exclamation-circle`],
// ['fas', `exclamation-triangle`],
// ['fas', `expand`],
// ['fas', `expand-alt`],
// ['fas', `expand-arrows-alt`],
// ['fas', `external-link-alt`],
// ['fas', `external-link-square-alt`],
// ['far', `eye`],
// ['fas', `eye`],
// ['fas', `eye-dropper`],
// ['far', `eye-slash`],
// ['fas', `eye-slash`],
// ['fas', `fan`],
// ['fas', `fast-backward`],
// ['fas', `fast-forward`],
// ['fas', `faucet`],
// ['fas', `fax`],
// ['fas', `feather`],
// ['fas', `feather-alt`],
// ['fas', `female`],
// ['fas', `fighter-jet`],
// ['far', `file`],
// ['fas', `file`],
// ['far', `file-alt`],
// ['fas', `file-alt`],
// ['far', `file-archive`],
// ['fas', `file-archive`],
// ['far', `file-audio`],
// ['fas', `file-audio`],
// ['far', `file-code`],
// ['fas', `file-code`],
// ['fas', `file-contract`],
// ['fas', `file-csv`],
// ['fas', `file-download`],
// ['far', `file-excel`],
// ['fas', `file-excel`],
// ['fas', `file-export`],
['far', `file-image`],
['fas', `file-image`],
['fas', `file-import`],
['fas', `file-invoice`],
['fas', `file-invoice-dollar`],
['fas', `file-medical`],
['fas', `file-medical-alt`],
['far', `file-pdf`],
['fas', `file-pdf`],
['far', `file-powerpoint`],
['fas', `file-powerpoint`],
['fas', `file-prescription`],
['fas', `file-signature`],
['fas', `file-upload`],
['far', `file-video`],
['fas', `file-video`],
['far', `file-word`],
['fas', `file-word`],
['fas', `fill`],
['fas', `fill-drip`],
['fas', `film`],
['fas', `filter`],
['fas', `fingerprint`],
['fas', `fire`],
['fas', `fire-alt`],
['fas', `fire-extinguisher`],
['fas', `first-aid`],
['fas', `fish`],
// ['fas', `fist-raised`],
// ['far', `flag`],
// ['fas', `flag`],
// ['fas', `flag-checkered`],
// ['fas', `flag-usa`],
// ['fas', `flask`],
// ['far', `flushed`],
// ['fas', `flushed`],
// ['far', `folder`],
// ['fas', `folder`],
// ['fas', `folder-minus`],
// ['far', `folder-open`],
// ['fas', `folder-open`],
// ['fas', `folder-plus`],
// ['fas', `font`],
// ['fas', `football-ball`],
// ['fas', `forward`],
// ['fas', `frog`],
// ['far', `frown`],
// ['fas', `frown`],
// ['far', `frown-open`],
// ['fas', `frown-open`],
// ['fas', `funnel-dollar`],
// ['far', `futbol`],
// ['fas', `futbol`],
// ['fas', `gamepad`],
// ['fas', `gas-pump`],
// ['fas', `gavel`],
// ['far', `gem`],
// ['fas', `gem`],
// ['fas', `genderless`],
// ['fas', `ghost`],
// ['fas', `gift`],
// ['fas', `gifts`],
// ['fas', `glass-cheers`],
// ['fas', `glass-martini`],
// ['fas', `glass-martini-alt`],
// ['fas', `glass-whiskey`],
// ['fas', `glasses`],
// ['fas', `globe`],
// ['fas', `globe-africa`],
// ['fas', `globe-americas`],
// ['fas', `globe-asia`],
// ['fas', `globe-europe`],
// ['fas', `golf-ball`],
// ['fas', `gopuram`],
// ['fas', `graduation-cap`],
// ['fas', `greater-than`],
// ['fas', `greater-than-equal`],
// ['far', `grimace`],
// ['fas', `grimace`],
// ['far', `grin`],
// ['fas', `grin`],
// ['far', `grin-alt`],
// ['fas', `grin-alt`],
// ['far', `grin-beam`],
// ['fas', `grin-beam`],
// ['far', `grin-beam-sweat`],
// ['fas', `grin-beam-sweat`],
// ['far', `grin-hearts`],
// ['fas', `grin-hearts`],
// ['far', `grin-squint`],
// ['fas', `grin-squint`],
// ['far', `grin-squint-tears`],
// ['fas', `grin-squint-tears`],
// ['far', `grin-stars`],
// ['fas', `grin-stars`],
// ['far', `grin-tears`],
// ['fas', `grin-tears`],
// ['far', `grin-tongue`],
// ['fas', `grin-tongue`],
// ['far', `grin-tongue-squint`],
// ['fas', `grin-tongue-squint`],
// ['far', `grin-tongue-wink`],
// ['fas', `grin-tongue-wink`],
// ['far', `grin-wink`],
// ['fas', `grin-wink`],
// ['fas', `grip-horizontal`],
// ['fas', `grip-lines`],
// ['fas', `grip-lines-vertical`],
// ['fas', `grip-vertical`],
['fas', `guitar`],
['fas', `h-square`],
['fas', `hamburger`],
['fas', `hammer`],
['fas', `hamsa`],
['fas', `hand-holding`],
['fas', `hand-holding-heart`],
['fas', `hand-holding-medical`],
['fas', `hand-holding-usd`],
['fas', `hand-holding-water`],
['far', `hand-lizard`],
['fas', `hand-lizard`],
['fas', `hand-middle-finger`],
['far', `hand-paper`],
['fas', `hand-paper`],
['far', `hand-peace`],
['fas', `hand-peace`],
['far', `hand-point-down`],
['fas', `hand-point-down`],
['far', `hand-point-left`],
['fas', `hand-point-left`],
['far', `hand-point-right`],
['fas', `hand-point-right`],
['far', `hand-point-up`],
['fas', `hand-point-up`],
['far', `hand-pointer`],
['fas', `hand-pointer`],
['far', `hand-rock`],
['fas', `hand-rock`],
['far', `hand-scissors`],
['fas', `hand-scissors`],
['fas', `hand-sparkles`],
['far', `hand-spock`],
['fas', `hand-spock`],
['fas', `hands`],
['fas', `hands-helping`],
['fas', `hands-wash`],
['far', `handshake`],
['fas', `handshake`],
['fas', `handshake-alt-slash`],
['fas', `handshake-slash`],
['fas', `hanukiah`],
['fas', `hard-hat`],
// ['fas', `hashtag`],
// ['fas', `hat-cowboy`],
// ['fas', `hat-cowboy-side`],
// ['fas', `hat-wizard`],
// ['far', `hdd`],
// ['fas', `hdd`],
// ['fas', `head-side-cough`],
// ['fas', `head-side-cough-slash`],
// ['fas', `head-side-mask`],
// ['fas', `head-side-virus`],
// ['fas', `heading`],
// ['fas', `headphones`],
// ['fas', `headphones-alt`],
// ['fas', `headset`],
// ['far', `heart`],
// ['fas', `heart`],
// ['fas', `heart-broken`],
// ['fas', `heartbeat`],
// ['fas', `helicopter`],
// ['fas', `highlighter`],
// ['fas', `hiking`],
// ['fas', `hippo`],
// ['fas', `history`],
// ['fas', `hockey-puck`],
// ['fas', `holly-berry`],
// ['fas', `home`],
// ['fas', `horse`],
// ['fas', `horse-head`],
// ['far', `hospital`],
// ['fas', `hospital`],
// ['fas', `hospital-alt`],
// ['fas', `hospital-symbol`],
// ['fas', `hospital-user`],
// ['fas', `hot-tub`],
// ['fas', `hotdog`],
// ['fas', `hotel`],
// ['far', `hourglass`],
// ['fas', `hourglass`],
// ['fas', `hourglass-end`],
// ['fas', `hourglass-half`],
// ['fas', `hourglass-start`],
// ['fas', `house-damage`],
// ['fas', `house-user`],
// ['fas', `hryvnia`],
// ['fas', `i-cursor`],
// ['fas', `ice-cream`],
// ['fas', `icicles`],
// ['fas', `icons`],
// ['far', `id-badge`],
// ['fas', `id-badge`],
// ['far', `id-card`],
// ['fas', `id-card`],
// ['fas', `id-card-alt`],
// ['fas', `igloo`],
// ['far', `image`],
// ['fas', `image`],
// ['far', `images`],
// ['fas', `images`],
// ['fas', `inbox`],
// ['fas', `indent`],
// ['fas', `industry`],
// ['fas', `infinity`],
// ['fas', `info`],
// ['fas', `info-circle`],
// ['fas', `italic`],
// ['fas', `jedi`],
// ['fas', `joint`],
// ['fas', `journal-whills`],
// ['fas', `kaaba`],
// ['fas', `key`],
// ['far', `keyboard`],
// ['fas', `keyboard`],
// ['fas', `khanda`],
// ['far', `kiss`],
// ['fas', `kiss`],
// ['far', `kiss-beam`],
// ['fas', `kiss-beam`],
// ['far', `kiss-wink-heart`],
// ['fas', `kiss-wink-heart`],
// ['fas', `kiwi-bird`],
// ['fas', `landmark`],
// ['fas', `language`],
// ['fas', `laptop`],
// ['fas', `laptop-code`],
// ['fas', `laptop-house`],
// ['fas', `laptop-medical`],
// ['far', `laugh`],
// ['fas', `laugh`],
// ['far', `laugh-beam`],
// ['fas', `laugh-beam`],
// ['far', `laugh-squint`],
// ['fas', `laugh-squint`],
// ['far', `laugh-wink`],
// ['fas', `laugh-wink`],
// ['fas', `layer-group`],
// ['fas', `leaf`],
// ['far', `lemon`],
// ['fas', `lemon`],
// ['fas', `less-than`],
// ['fas', `less-than-equal`],
// ['fas', `level-down-alt`],
// ['fas', `level-up-alt`],
// ['far', `life-ring`],
// ['fas', `life-ring`],
// ['far', `lightbulb`],
// ['fas', `lightbulb`],
// ['fas', `link`],
// ['fas', `lira-sign`],
// ['fas', `list`],
// ['far', `list-alt`],
// ['fas', `list-alt`],
// ['fas', `list-ol`],
// ['fas', `list-ul`],
// ['fas', `location-arrow`],
// ['fas', `lock`],
// ['fas', `lock-open`],
// ['fas', `long-arrow-alt-down`],
// ['fas', `long-arrow-alt-left`],
// ['fas', `long-arrow-alt-right`],
// ['fas', `long-arrow-alt-up`],
// ['fas', `low-vision`],
// ['fas', `luggage-cart`],
// ['fas', `lungs`],
// ['fas', `lungs-virus`],
// ['fas', `magic`],
// ['fas', `magnet`],
// ['fas', `mail-bulk`],
// ['fas', `male`],
// ['far', `map`],
// ['fas', `map`],
// ['fas', `map-marked`],
// ['fas', `map-marked-alt`],
// ['fas', `map-marker`],
// ['fas', `map-marker-alt`],
// ['fas', `map-pin`],
// ['fas', `map-signs`],
// ['fas', `marker`],
// ['fas', `mars`],
// ['fas', `mars-double`],
// ['fas', `mars-stroke`],
// ['fas', `mars-stroke-h`],
// ['fas', `mars-stroke-v`],
// ['fas', `mask`],
// ['fas', `medal`],
// ['fas', `medkit`],
// ['far', `meh`],
// ['fas', `meh`],
// ['far', `meh-blank`],
// ['fas', `meh-blank`],
// ['far', `meh-rolling-eyes`],
// ['fas', `meh-rolling-eyes`],
// ['fas', `memory`],
// ['fas', `menorah`],
// ['fas', `mercury`],
// ['fas', `meteor`],
// ['fas', `microchip`],
// ['fas', `microphone`],
// ['fas', `microphone-alt`],
// ['fas', `microphone-alt-slash`],
// ['fas', `microphone-slash`],
// ['fas', `microscope`],
// ['fas', `minus`],
// ['fas', `minus-circle`],
// ['far', `minus-square`],
// ['fas', `minus-square`],
// ['fas', `mitten`],
// ['fas', `mobile`],
// ['fas', `mobile-alt`],
// ['fas', `money-bill`],
// ['far', `money-bill-alt`],
// ['fas', `money-bill-alt`],
// ['fas', `money-bill-wave`],
// ['fas', `money-bill-wave-alt`],
// ['fas', `money-check`],
// ['fas', `money-check-alt`],
// ['fas', `monument`],
// ['far', `moon`],
// ['fas', `moon`],
// ['fas', `mortar-pestle`],
// ['fas', `mosque`],
// ['fas', `motorcycle`],
// ['fas', `mountain`],
// ['fas', `mouse`],
// ['fas', `mouse-pointer`],
// ['fas', `mug-hot`],
// ['fas', `music`],
// ['fas', `network-wired`],
// ['fas', `neuter`],
// ['far', `newspaper`],
// ['fas', `newspaper`],
// ['fas', `not-equal`],
// ['fas', `notes-medical`],
// ['far', `object-group`],
// ['fas', `object-group`],
// ['far', `object-ungroup`],
// ['fas', `object-ungroup`],
// ['fas', `oil-can`],
// ['fas', `om`],
// ['fas', `otter`],
// ['fas', `outdent`],
// ['fas', `pager`],
// ['fas', `paint-brush`],
// ['fas', `paint-roller`],
// ['fas', `palette`],
// ['fas', `pallet`],
// ['far', `paper-plane`],
// ['fas', `paper-plane`],
// ['fas', `paperclip`],
// ['fas', `parachute-box`],
// ['fas', `paragraph`],
// ['fas', `parking`],
// ['fas', `passport`],
// ['fas', `pastafarianism`],
// ['fas', `paste`],
// ['fas', `pause`],
// ['far', `pause-circle`],
// ['fas', `pause-circle`],
// ['fas', `paw`],
// ['fas', `peace`],
// ['fas', `pen`],
// ['fas', `pen-alt`],
// ['fas', `pen-fancy`],
// ['fas', `pen-nib`],
// ['fas', `pen-square`],
// ['fas', `pencil-alt`],
// ['fas', `pencil-ruler`],
// ['fas', `people-arrows`],
// ['fas', `people-carry`],
// ['fas', `pepper-hot`],
// ['fas', `percent`],
// ['fas', `percentage`],
// ['fas', `person-booth`],
// ['fas', `phone`],
// ['fas', `phone-alt`],
// ['fas', `phone-slash`],
// ['fas', `phone-square`],
// ['fas', `phone-square-alt`],
// ['fas', `phone-volume`],
// ['fas', `photo-video`],
// ['fas', `piggy-bank`],
// ['fas', `pills`],
// ['fas', `pizza-slice`],
// ['fas', `place-of-worship`],
// ['fas', `plane`],
// ['fas', `plane-arrival`],
// ['fas', `plane-departure`],
// ['fas', `plane-slash`],
// ['fas', `play`],
// ['far', `play-circle`],
// ['fas', `play-circle`],
// ['fas', `plug`],
// ['fas', `plus`],
// ['fas', `plus-circle`],
// ['far', `plus-square`],
// ['fas', `plus-square`],
// ['fas', `podcast`],
// ['fas', `poll`],
// ['fas', `poll-h`],
// ['fas', `poo`],
// ['fas', `poo-storm`],
// ['fas', `poop`],
// ['fas', `portrait`],
// ['fas', `pound-sign`],
// ['fas', `power-off`],
// ['fas', `pray`],
// ['fas', `praying-hands`],
// ['fas', `prescription`],
// ['fas', `prescription-bottle`],
// ['fas', `prescription-bottle-alt`],
// ['fas', `print`],
// ['fas', `procedures`],
// ['fas', `project-diagram`],
// ['fas', `pump-medical`],
// ['fas', `pump-soap`],
// ['fas', `puzzle-piece`],
// ['fas', `qrcode`],
// ['fas', `question`],
// ['far', `question-circle`],
// ['fas', `question-circle`],
// ['fas', `quidditch`],
// ['fas', `quote-left`],
// ['fas', `quote-right`],
// ['fas', `quran`],
// ['fas', `radiation`],
// ['fas', `radiation-alt`],
// ['fas', `rainbow`],
// ['fas', `random`],
// ['fas', `receipt`],
// ['fas', `record-vinyl`],
// ['fas', `recycle`],
// ['fas', `redo`],
// ['fas', `redo-alt`],
// ['far', `registered`],
// ['fas', `registered`],
// ['fas', `remove-format`],
// ['fas', `reply`],
// ['fas', `reply-all`],
// ['fas', `republican`],
// ['fas', `restroom`],
// ['fas', `retweet`],
// ['fas', `ribbon`],
// ['fas', `ring`],
// ['fas', `road`],
// ['fas', `robot`],
// ['fas', `rocket`],
// ['fas', `route`],
// ['fas', `rss`],
// ['fas', `rss-square`],
// ['fas', `ruble-sign`],
// ['fas', `ruler`],
// ['fas', `ruler-combined`],
// ['fas', `ruler-horizontal`],
// ['fas', `ruler-vertical`],
// ['fas', `running`],
// ['fas', `rupee-sign`],
// ['far', `sad-cry`],
// ['fas', `sad-cry`],
// ['far', `sad-tear`],
// ['fas', `sad-tear`],
// ['fas', `satellite`],
// ['fas', `satellite-dish`],
// ['far', `save`],
// ['fas', `save`],
// ['fas', `school`],
// ['fas', `screwdriver`],
// ['fas', `scroll`],
// ['fas', `sd-card`],
// ['fas', `search`],
// ['fas', `search-dollar`],
// ['fas', `search-location`],
// ['fas', `search-minus`],
// ['fas', `search-plus`],
// ['fas', `seedling`],
// ['fas', `server`],
// ['fas', `shapes`],
// ['fas', `share`],
// ['fas', `share-alt`],
// ['fas', `share-alt-square`],
// ['far', `share-square`],
// ['fas', `share-square`],
// ['fas', `shekel-sign`],
// ['fas', `shield-alt`],
// ['fas', `shield-virus`],
// ['fas', `ship`],
// ['fas', `shipping-fast`],
// ['fas', `shoe-prints`],
// ['fas', `shopping-bag`],
// ['fas', `shopping-basket`],
// ['fas', `shopping-cart`],
// ['fas', `shower`],
// ['fas', `shuttle-van`],
// ['fas', `sign`],
// ['fas', `sign-in-alt`],
// ['fas', `sign-language`],
// ['fas', `sign-out-alt`],
// ['fas', `signal`],
// ['fas', `signature`],
// ['fas', `sim-card`],
// ['fas', `sitemap`],
// ['fas', `skating`],
// ['fas', `skiing`],
// ['fas', `skiing-nordic`],
// ['fas', `skull`],
// ['fas', `skull-crossbones`],
// ['fas', `slash`],
// ['fas', `sleigh`],
// ['fas', `sliders-h`],
// ['far', `smile`],
// ['fas', `smile`],
// ['far', `smile-beam`],
// ['fas', `smile-beam`],
// ['far', `smile-wink`],
// ['fas', `smile-wink`],
// ['fas', `smog`],
// ['fas', `smoking`],
// ['fas', `smoking-ban`],
// ['fas', `sms`],
// ['fas', `snowboarding`],
// ['far', `snowflake`],
// ['fas', `snowflake`],
// ['fas', `snowman`],
// ['fas', `snowplow`],
// ['fas', `soap`],
// ['fas', `socks`],
// ['fas', `solar-panel`],
// ['fas', `sort`],
// ['fas', `sort-alpha-down`],
// ['fas', `sort-alpha-down-alt`],
// ['fas', `sort-alpha-up`],
// ['fas', `sort-alpha-up-alt`],
// ['fas', `sort-amount-down`],
// ['fas', `sort-amount-down-alt`],
// ['fas', `sort-amount-up`],
// ['fas', `sort-amount-up-alt`],
// ['fas', `sort-down`],
// ['fas', `sort-numeric-down`],
// ['fas', `sort-numeric-down-alt`],
// ['fas', `sort-numeric-up`],
// ['fas', `sort-numeric-up-alt`],
// ['fas', `sort-up`],
// ['fas', `spa`],
// ['fas', `space-shuttle`],
// ['fas', `spell-check`],
// ['fas', `spider`],
// ['fas', `spinner`],
// ['fas', `splotch`],
// ['fas', `spray-can`],
// ['far', `square`],
// ['fas', `square`],
// ['fas', `square-full`],
// ['fas', `square-root-alt`],
// ['fas', `stamp`],
// ['far', `star`],
// ['fas', `star`],
// ['fas', `star-and-crescent`],
// ['far', `star-half`],
// ['fas', `star-half`],
// ['fas', `star-half-alt`],
// ['fas', `star-of-david`],
// ['fas', `star-of-life`],
// ['fas', `step-backward`],
// ['fas', `step-forward`],
// ['fas', `stethoscope`],
// ['far', `sticky-note`],
// ['fas', `sticky-note`],
// ['fas', `stop`],
// ['far', `stop-circle`],
// ['fas', `stop-circle`],
// ['fas', `stopwatch`],
// ['fas', `stopwatch-20`],
// ['fas', `store`],
// ['fas', `store-alt`],
// ['fas', `store-alt-slash`],
// ['fas', `store-slash`],
// ['fas', `stream`],
// ['fas', `street-view`],
// ['fas', `strikethrough`],
// ['fas', `stroopwafel`],
// ['fas', `subscript`],
// ['fas', `subway`],
// ['fas', `suitcase`],
// ['fas', `suitcase-rolling`],
// ['far', `sun`],
// ['fas', `sun`],
// ['fas', `superscript`],
// ['far', `surprise`],
// ['fas', `surprise`],
// ['fas', `swatchbook`],
// ['fas', `swimmer`],
// ['fas', `swimming-pool`],
// ['fas', `synagogue`],
// ['fas', `sync`],
// ['fas', `sync-alt`],
// ['fas', `syringe`],
// ['fas', `table`],
// ['fas', `table-tennis`],
// ['fas', `tablet`],
// ['fas', `tablet-alt`],
// ['fas', `tablets`],
// ['fas', `tachometer-alt`],
// ['fas', `tag`],
// ['fas', `tags`],
// ['fas', `tape`],
// ['fas', `tasks`],
// ['fas', `taxi`],
// ['fas', `teeth`],
// ['fas', `teeth-open`],
// ['fas', `temperature-high`],
// ['fas', `temperature-low`],
// ['fas', `tenge`],
// ['fas', `terminal`],
// ['fas', `text-height`],
// ['fas', `text-width`],
// ['fas', `th`],
// ['fas', `th-large`],
// ['fas', `th-list`],
// ['fas', `theater-masks`],
// ['fas', `thermometer`],
// ['fas', `thermometer-empty`],
// ['fas', `thermometer-full`],
// ['fas', `thermometer-half`],
// ['fas', `thermometer-quarter`],
// ['fas', `thermometer-three-quarters`],
// ['far', `thumbs-down`],
// ['fas', `thumbs-down`],
// ['far', `thumbs-up`],
// ['fas', `thumbs-up`],
// ['fas', `thumbtack`],
// ['fas', `ticket-alt`],
// ['fas', `times`],
// ['far', `times-circle`],
// ['fas', `times-circle`],
// ['fas', `tint`],
// ['fas', `tint-slash`],
// ['far', `tired`],
// ['fas', `tired`],
// ['fas', `toggle-off`],
// ['fas', `toggle-on`],
// ['fas', `toilet`],
// ['fas', `toilet-paper`],
// ['fas', `toilet-paper-slash`],
// ['fas', `toolbox`],
// ['fas', `tools`],
// ['fas', `tooth`],
// ['fas', `torah`],
// ['fas', `torii-gate`],
// ['fas', `tractor`],
// ['fas', `trademark`],
// ['fas', `traffic-light`],
// ['fas', `trailer`],
// ['fas', `train`],
// ['fas', `tram`],
// ['fas', `transgender`],
// ['fas', `transgender-alt`],
// ['fas', `trash`],
// ['far', `trash-alt`],
// ['fas', `trash-alt`],
// ['fas', `trash-restore`],
// ['fas', `trash-restore-alt`],
// ['fas', `tree`],
// ['fas', `trophy`],
// ['fas', `truck`],
// ['fas', `truck-loading`],
// ['fas', `truck-monster`],
// ['fas', `truck-moving`],
// ['fas', `truck-pickup`],
// ['fas', `tshirt`],
// ['fas', `tty`],
// ['fas', `tv`],
// ['fas', `umbrella`],
// ['fas', `umbrella-beach`],
// ['fas', `underline`],
// ['fas', `undo`],
// ['fas', `undo-alt`],
// ['fas', `universal-access`],
// ['fas', `university`],
// ['fas', `unlink`],
// ['fas', `unlock`],
// ['fas', `unlock-alt`],
// ['fas', `upload`],
// ['far', `user`],
// ['fas', `user`],
// ['fas', `user-alt`],
// ['fas', `user-alt-slash`],
// ['fas', `user-astronaut`],
// ['fas', `user-check`],
// ['far', `user-circle`],
// ['fas', `user-circle`],
// ['fas', `user-clock`],
// ['fas', `user-cog`],
// ['fas', `user-edit`],
// ['fas', `user-friends`],
// ['fas', `user-graduate`],
// ['fas', `user-injured`],
// ['fas', `user-lock`],
// ['fas', `user-md`],
// ['fas', `user-minus`],
// ['fas', `user-ninja`],
// ['fas', `user-nurse`],
// ['fas', `user-plus`],
// ['fas', `user-secret`],
// ['fas', `user-shield`],
// ['fas', `user-slash`],
// ['fas', `user-tag`],
// ['fas', `user-tie`],
// ['fas', `user-times`],
// ['fas', `users`],
// ['fas', `users-cog`],
// ['fas', `utensil-spoon`],
// ['fas', `utensils`],
// ['fas', `vector-square`],
// ['fas', `venus`],
// ['fas', `venus-double`],
// ['fas', `venus-mars`],
// ['fas', `vial`],
// ['fas', `vials`],
// ['fas', `video`],
// ['fas', `video-slash`],
// ['fas', `vihara`],
// ['fas', `virus`],
// ['fas', `virus-slash`],
// ['fas', `viruses`],
// ['fas', `voicemail`],
// ['fas', `volleyball-ball`],
// ['fas', `volume-down`],
// ['fas', `volume-mute`],
// ['fas', `volume-off`],
// ['fas', `volume-up`],
// ['fas', `vote-yea`],
// ['fas', `vr-cardboard`],
// ['fas', `walking`],
['fas', `wallet`],
['fas', `warehouse`],
['fas', `water`],
['fas', `wave-square`],
['fas', `weight`],
['fas', `weight-hanging`],
['fas', `wheelchair`],
['fas', `wifi`],
['fas', `wind`],
['far', `window-close`],
['fas', `window-close`],
['far', `window-maximize`],
['fas', `window-maximize`],
['far', `window-minimize`],
['fas', `window-minimize`],
['far', `window-restore`],
['fas', `window-restore`],
['fas', `wine-bottle`],
['fas', `wine-glass`],
['fas', `wine-glass-alt`],
['fas', `won-sign`],
['fas', `wrench`],
['fas', `x-ray`],
['fas', `yen-sign`],
['fas', `yin-yang`]
]